### ISSUE TITLE
 throw er; // Unhandled 'error' event in ETIMEDOUT

### ISSUE THREAD

**Issue by vizardkill** [shaozi/ldap-authentication#4]
I want to report an error, if the authentication function cannot connect to the server, you should be able to control it through a try catch or a promise, however it is not possible.

**attached my code**

```javascript
const config = (strUser, strPass) => {
    let options = {
        ldapOpts: {
            url: process.env.LDAP_URL,
        },
        adminDn: process.env.LDAP_ADMINDN,
        adminPassword: process.env.LDAP_ADMINPASS,
        userSearchBase: process.env.LDAP_SEARCHBASE,
        usernameAttribute: process.env.LDAP_SEARCHATTRIBUTE,
        username: strUser,
        userPassword: strPass
    }
    return options
};

const auth = () => {
    try {
            let options = config(strUser, strPass);
            let user = await authenticate(options);

            let userData = {
                strNombre: user.givenName,
                strApellidos: user.sn,
                strEmail: user.mail,
                strUsuario: user.sAMAccountName,
                strCargo: user.title,
                strArea: user.description,
            };

            let token = jwt.sign(
                {
                    ...userData,
                },
                { key: privateKey, passphrase: process.env.TOKEN_SEED },
                { expiresIn: process.env.TOKEN_EXPIRATION, algorithm: "RS256" }
            );

            let result = {
                error: false,
                data: token,
            };
            return result;
        } catch (error) {
            let result = {
                error: true,
                msg: "Usuario o contraseña incorrectos.",
                info: error.message,
            };
            return result;
        }



}
```

**I enclose the error:** 

```text
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT localhost:389
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Emitted 'error' event on Client instance at:
    at Backoff.<anonymous> (D:\Documents\NodeProjects\React\Choucair\DAT_ArquitecturaDeDatos\backend\node_modules\ldapjs\lib\client\client.js:1228:12)
    at Backoff.emit (events.js:315:20)
    at Backoff.backoff (D:\Documents\NodeProjects\React\Choucair\DAT_ArquitecturaDeDatos\backend\node_modules\backoff\lib\backoff.js:41:14)
    at D:\Documents\NodeProjects\React\Choucair\DAT_ArquitecturaDeDatos\backend\node_modules\ldapjs\lib\client\client.js:1214:15
    at f (D:\Documents\NodeProjects\React\Choucair\DAT_ArquitecturaDeDatos\backend\node_modules\once\once.js:25:25)
    at Socket.onResult (D:\Documents\NodeProjects\React\Choucair\DAT_ArquitecturaDeDatos\backend\node_modules\ldapjs\lib\client\client.js:1016:7)     
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: 'localhost',
  port: 389
}
```

**Comment by shaozi** [comment]
I will take a look
